FROM node:22-alpine AS deps
WORKDIR /app
RUN apk add --no-cache libc6-compat
COPY package.json package-lock.json .npmrc ./
RUN --mount=type=cache,target=/root/.npm \
    npm ci

FROM node:22-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules

ARG NEXT_PUBLIC_APPWRITE_ENDPOINT
ARG NEXT_PUBLIC_APPWRITE_PROJECT_ID
ARG NEXT_PUBLIC_APPWRITE_DATABASE_ID
ARG NEXT_PUBLIC_APPWRITE_SOCIETIES_COLLECTION_ID
ARG NEXT_PUBLIC_APPWRITE_EVENTS_COLLECTION_ID
ARG NEXT_PUBLIC_APPWRITE_EXECOM_COLLECTION_ID
ARG NEXT_PUBLIC_APPWRITE_MEMBERS_COLLECTION_ID
ARG NEXT_PUBLIC_APPWRITE_EVENT_REGISTRATIONS_COLLECTION_ID
ARG NEXT_PUBLIC_APPWRITE_EMAIL_LOGS_COLLECTION_ID
ARG NEXT_PUBLIC_APPWRITE_SOCIETY_IMAGES_BUCKET_ID
ARG NEXT_PUBLIC_UPI_ID
ARG NEXT_PUBLIC_MERCHANT_NAME
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_ENABLE_PAYMENTS
ARG NEXT_PUBLIC_ENABLE_EMAILS
ARG NEXT_PUBLIC_ENABLE_PASSKEYS

ENV NEXT_PUBLIC_APPWRITE_ENDPOINT=$NEXT_PUBLIC_APPWRITE_ENDPOINT
ENV NEXT_PUBLIC_APPWRITE_PROJECT_ID=$NEXT_PUBLIC_APPWRITE_PROJECT_ID
ENV NEXT_PUBLIC_APPWRITE_DATABASE_ID=$NEXT_PUBLIC_APPWRITE_DATABASE_ID
ENV NEXT_PUBLIC_APPWRITE_SOCIETIES_COLLECTION_ID=$NEXT_PUBLIC_APPWRITE_SOCIETIES_COLLECTION_ID
ENV NEXT_PUBLIC_APPWRITE_EVENTS_COLLECTION_ID=$NEXT_PUBLIC_APPWRITE_EVENTS_COLLECTION_ID
ENV NEXT_PUBLIC_APPWRITE_EXECOM_COLLECTION_ID=$NEXT_PUBLIC_APPWRITE_EXECOM_COLLECTION_ID
ENV NEXT_PUBLIC_APPWRITE_MEMBERS_COLLECTION_ID=$NEXT_PUBLIC_APPWRITE_MEMBERS_COLLECTION_ID
ENV NEXT_PUBLIC_APPWRITE_EVENT_REGISTRATIONS_COLLECTION_ID=$NEXT_PUBLIC_APPWRITE_EVENT_REGISTRATIONS_COLLECTION_ID
ENV NEXT_PUBLIC_APPWRITE_EMAIL_LOGS_COLLECTION_ID=$NEXT_PUBLIC_APPWRITE_EMAIL_LOGS_COLLECTION_ID
ENV NEXT_PUBLIC_APPWRITE_SOCIETY_IMAGES_BUCKET_ID=$NEXT_PUBLIC_APPWRITE_SOCIETY_IMAGES_BUCKET_ID
ENV NEXT_PUBLIC_UPI_ID=$NEXT_PUBLIC_UPI_ID
ENV NEXT_PUBLIC_MERCHANT_NAME=$NEXT_PUBLIC_MERCHANT_NAME
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_ENABLE_PAYMENTS=$NEXT_PUBLIC_ENABLE_PAYMENTS
ENV NEXT_PUBLIC_ENABLE_EMAILS=$NEXT_PUBLIC_ENABLE_EMAILS
ENV NEXT_PUBLIC_ENABLE_PASSKEYS=$NEXT_PUBLIC_ENABLE_PASSKEYS

COPY . .
RUN --mount=type=cache,target=/app/.next/cache \
    npm run build

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME="0.0.0.0"

RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json /app/next.config.mjs ./

COPY --from=builder /app/node_modules ./node_modules
RUN npm prune --omit=dev && npm cache clean --force

COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next

USER nextjs
EXPOSE 3000
CMD ["node_modules/.bin/next", "start"]
