/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    users: User;
    societies: Society;
    execom: Execom;
    events: Event;
    registrations: Registration;
    orders: Order;
    coupons: Coupon;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    societies: SocietiesSelect<false> | SocietiesSelect<true>;
    execom: ExecomSelect<false> | ExecomSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    registrations: RegistrationsSelect<false> | RegistrationsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  email: string;
  emailVerified?: string | null;
  name?: string | null;
  image?: string | null;
  phone?: string | null;
  sahrdayaEmail?: string | null;
  semester?: ('S1' | 'S2' | 'S3' | 'S4' | 'S5' | 'S6' | 'S7' | 'S8') | null;
  department?: ('CSE' | 'ECE' | 'EEE' | 'ME' | 'CE' | 'IT' | 'AEI' | 'Other') | null;
  section?: ('A' | 'B' | 'C' | 'D') | null;
  rollNumber?: string | null;
  foodPreference?: string | null;
  residence?: string | null;
  profileCompleted?: boolean | null;
  role: 'user' | 'admin';
  teams?:
    | {
        team?: string | null;
        id?: string | null;
      }[]
    | null;
  appwriteUserId?: string | null;
  accounts?:
    | {
        provider: string;
        providerAccountId: string;
        type: 'oidc' | 'oauth' | 'email' | 'webauthn';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "societies".
 */
export interface Society {
  id: number;
  name: string;
  slug: string;
  bio?: string | null;
  logo?: (number | null) | Media;
  banner?: (number | null) | Media;
  chairs?: (string | User)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "execom".
 */
export interface Execom {
  id: number;
  name: string;
  position: string;
  society?: (number | null) | Society;
  photo?: (number | null) | Media;
  order?: number | null;
  batch?: string | null;
  linkedin?: string | null;
  email?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  date: string;
  endDate?: string | null;
  venue: string;
  price: number;
  society: number | Society;
  banner?: (number | null) | Media;
  status?: ('draft' | 'published' | 'archived' | 'completed' | 'cancelled') | null;
  maxCapacity?: number | null;
  registeredCount?: number | null;
  checkedInCount?: number | null;
  registrationOpen?: boolean | null;
  registrationStart?: string | null;
  registrationDeadline?: string | null;
  formTemplate?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  enableWaitlist?: boolean | null;
  waitlistLimit?: number | null;
  waitlistCount?: number | null;
  isPaid?: boolean | null;
  ieeeMemberPrice?: number | null;
  nonMemberPrice?: number | null;
  earlyBirdPrice?: number | null;
  earlyBirdDeadline?: string | null;
  pricingTiers?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  currency?: string | null;
  checkInEnabled?: boolean | null;
  selfCheckIn?: boolean | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  externalLink?: string | null;
  tags?: string | null;
  category?: ('technical' | 'cultural' | 'workshop' | 'seminar' | 'competition' | 'other') | null;
  speakers?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  schedule?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  faqs?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  isDeleted?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations".
 */
export interface Registration {
  id: number;
  user: string | User;
  event: number | Event;
  userName?: string | null;
  userEmail?: string | null;
  userPhone?: string | null;
  formResponses?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  paymentStatus?: ('pending' | 'paid' | 'completed' | 'failed' | 'refunded' | 'not_required') | null;
  paymentAmount?: number | null;
  paymentTicketId?: string | null;
  registrationStatus?: ('pending' | 'confirmed' | 'cancelled' | 'expired') | null;
  registrationDate?: string | null;
  /**
   * Embedded ticket data: { ticket_id, ticket_code, qr_code, is_scanned, issued_at }
   */
  ticket?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  checkedIn?: boolean | null;
  checkedInAt?: string | null;
  checkedInBy?: (string | null) | User;
  lastCheckInLocation?: string | null;
  /**
   * Multi-location check-in timeline
   */
  checkInHistory?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  user: string | User;
  registration: number | Registration;
  amount: number;
  paymentMethod?: ('upi' | 'cash') | null;
  paymentStatus?: ('pending' | 'paid' | 'failed' | 'refunded') | null;
  ddmTicketId?: string | null;
  ddmResponse?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  coupon?: (number | null) | Coupon;
  discountedAmount?: number | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: number;
  code: string;
  discountType: 'percentage' | 'fixed';
  discountValue: number;
  maxUses?: number | null;
  usedCount?: number | null;
  expiresAt?: string | null;
  event?: (number | null) | Event;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'societies';
        value: number | Society;
      } | null)
    | ({
        relationTo: 'execom';
        value: number | Execom;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'registrations';
        value: number | Registration;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'coupons';
        value: number | Coupon;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  id?: T;
  email?: T;
  emailVerified?: T;
  name?: T;
  image?: T;
  phone?: T;
  sahrdayaEmail?: T;
  semester?: T;
  department?: T;
  section?: T;
  rollNumber?: T;
  foodPreference?: T;
  residence?: T;
  profileCompleted?: T;
  role?: T;
  teams?:
    | T
    | {
        team?: T;
        id?: T;
      };
  appwriteUserId?: T;
  accounts?:
    | T
    | {
        provider?: T;
        providerAccountId?: T;
        type?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "societies_select".
 */
export interface SocietiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  bio?: T;
  logo?: T;
  banner?: T;
  chairs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "execom_select".
 */
export interface ExecomSelect<T extends boolean = true> {
  name?: T;
  position?: T;
  society?: T;
  photo?: T;
  order?: T;
  batch?: T;
  linkedin?: T;
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  date?: T;
  endDate?: T;
  venue?: T;
  price?: T;
  society?: T;
  banner?: T;
  status?: T;
  maxCapacity?: T;
  registeredCount?: T;
  checkedInCount?: T;
  registrationOpen?: T;
  registrationStart?: T;
  registrationDeadline?: T;
  formTemplate?: T;
  enableWaitlist?: T;
  waitlistLimit?: T;
  waitlistCount?: T;
  isPaid?: T;
  ieeeMemberPrice?: T;
  nonMemberPrice?: T;
  earlyBirdPrice?: T;
  earlyBirdDeadline?: T;
  pricingTiers?: T;
  currency?: T;
  checkInEnabled?: T;
  selfCheckIn?: T;
  contactEmail?: T;
  contactPhone?: T;
  externalLink?: T;
  tags?: T;
  category?: T;
  speakers?: T;
  schedule?: T;
  faqs?: T;
  isDeleted?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations_select".
 */
export interface RegistrationsSelect<T extends boolean = true> {
  user?: T;
  event?: T;
  userName?: T;
  userEmail?: T;
  userPhone?: T;
  formResponses?: T;
  paymentStatus?: T;
  paymentAmount?: T;
  paymentTicketId?: T;
  registrationStatus?: T;
  registrationDate?: T;
  ticket?: T;
  checkedIn?: T;
  checkedInAt?: T;
  checkedInBy?: T;
  lastCheckInLocation?: T;
  checkInHistory?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  user?: T;
  registration?: T;
  amount?: T;
  paymentMethod?: T;
  paymentStatus?: T;
  ddmTicketId?: T;
  ddmResponse?: T;
  coupon?: T;
  discountedAmount?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  code?: T;
  discountType?: T;
  discountValue?: T;
  maxUses?: T;
  usedCount?: T;
  expiresAt?: T;
  event?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}