/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSocietiesRouteImport } from './routes/admin/societies'
import { Route as AdminRegistrationsRouteImport } from './routes/admin/registrations'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminCheckInRouteImport } from './routes/admin/check-in'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as PublicSocietiesRouteImport } from './routes/_public.societies'
import { Route as PublicEventsRouteImport } from './routes/_public.events'
import { Route as AdminEventsNewRouteImport } from './routes/admin/events.new'
import { Route as AdminEventsEventIdRouteImport } from './routes/admin/events.$eventId'
import { Route as AdminCheckInEventIdRouteImport } from './routes/admin/check-in.$eventId'
import { Route as PublicSocietiesSlugRouteImport } from './routes/_public.societies.$slug'
import { Route as PublicEventsEventIdRouteImport } from './routes/_public.events.$eventId'
import { Route as AdminEventsEventIdEditRouteImport } from './routes/admin/events.$eventId.edit'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSocietiesRoute = AdminSocietiesRouteImport.update({
  id: '/admin/societies',
  path: '/admin/societies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/admin/registrations',
  path: '/admin/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCheckInRoute = AdminCheckInRouteImport.update({
  id: '/admin/check-in',
  path: '/admin/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSocietiesRoute = PublicSocietiesRouteImport.update({
  id: '/societies',
  path: '/societies',
  getParentRoute: () => PublicRoute,
} as any)
const PublicEventsRoute = PublicEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => PublicRoute,
} as any)
const AdminEventsNewRoute = AdminEventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminEventsRoute,
} as any)
const AdminEventsEventIdRoute = AdminEventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => AdminEventsRoute,
} as any)
const AdminCheckInEventIdRoute = AdminCheckInEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => AdminCheckInRoute,
} as any)
const PublicSocietiesSlugRoute = PublicSocietiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicSocietiesRoute,
} as any)
const PublicEventsEventIdRoute = PublicEventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => PublicEventsRoute,
} as any)
const AdminEventsEventIdEditRoute = AdminEventsEventIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminEventsEventIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/events': typeof PublicEventsRouteWithChildren
  '/societies': typeof PublicSocietiesRouteWithChildren
  '/admin': typeof AdminLayoutRoute
  '/admin/check-in': typeof AdminCheckInRouteWithChildren
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/societies': typeof AdminSocietiesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/': typeof AdminIndexRoute
  '/events/$eventId': typeof PublicEventsEventIdRoute
  '/societies/$slug': typeof PublicSocietiesSlugRoute
  '/admin/check-in/$eventId': typeof AdminCheckInEventIdRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRouteWithChildren
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/events/$eventId/edit': typeof AdminEventsEventIdEditRoute
}
export interface FileRoutesByTo {
  '/events': typeof PublicEventsRouteWithChildren
  '/societies': typeof PublicSocietiesRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/check-in': typeof AdminCheckInRouteWithChildren
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/societies': typeof AdminSocietiesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof PublicIndexRoute
  '/events/$eventId': typeof PublicEventsEventIdRoute
  '/societies/$slug': typeof PublicSocietiesSlugRoute
  '/admin/check-in/$eventId': typeof AdminCheckInEventIdRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRouteWithChildren
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/events/$eventId/edit': typeof AdminEventsEventIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_public/events': typeof PublicEventsRouteWithChildren
  '/_public/societies': typeof PublicSocietiesRouteWithChildren
  '/admin/_layout': typeof AdminLayoutRoute
  '/admin/check-in': typeof AdminCheckInRouteWithChildren
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/societies': typeof AdminSocietiesRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_public/events/$eventId': typeof PublicEventsEventIdRoute
  '/_public/societies/$slug': typeof PublicSocietiesSlugRoute
  '/admin/check-in/$eventId': typeof AdminCheckInEventIdRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRouteWithChildren
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/events/$eventId/edit': typeof AdminEventsEventIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/societies'
    | '/admin'
    | '/admin/check-in'
    | '/admin/events'
    | '/admin/payments'
    | '/admin/registrations'
    | '/admin/societies'
    | '/admin/users'
    | '/auth/callback'
    | '/admin/'
    | '/events/$eventId'
    | '/societies/$slug'
    | '/admin/check-in/$eventId'
    | '/admin/events/$eventId'
    | '/admin/events/new'
    | '/admin/events/$eventId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/events'
    | '/societies'
    | '/admin'
    | '/admin/check-in'
    | '/admin/events'
    | '/admin/payments'
    | '/admin/registrations'
    | '/admin/societies'
    | '/admin/users'
    | '/auth/callback'
    | '/'
    | '/events/$eventId'
    | '/societies/$slug'
    | '/admin/check-in/$eventId'
    | '/admin/events/$eventId'
    | '/admin/events/new'
    | '/admin/events/$eventId/edit'
  id:
    | '__root__'
    | '/_public'
    | '/_public/events'
    | '/_public/societies'
    | '/admin/_layout'
    | '/admin/check-in'
    | '/admin/events'
    | '/admin/payments'
    | '/admin/registrations'
    | '/admin/societies'
    | '/admin/users'
    | '/auth/callback'
    | '/_public/'
    | '/admin/'
    | '/_public/events/$eventId'
    | '/_public/societies/$slug'
    | '/admin/check-in/$eventId'
    | '/admin/events/$eventId'
    | '/admin/events/new'
    | '/admin/events/$eventId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminLayoutRoute: typeof AdminLayoutRoute
  AdminCheckInRoute: typeof AdminCheckInRouteWithChildren
  AdminEventsRoute: typeof AdminEventsRouteWithChildren
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRoute
  AdminSocietiesRoute: typeof AdminSocietiesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/societies': {
      id: '/admin/societies'
      path: '/admin/societies'
      fullPath: '/admin/societies'
      preLoaderRoute: typeof AdminSocietiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/admin/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/check-in': {
      id: '/admin/check-in'
      path: '/admin/check-in'
      fullPath: '/admin/check-in'
      preLoaderRoute: typeof AdminCheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/societies': {
      id: '/_public/societies'
      path: '/societies'
      fullPath: '/societies'
      preLoaderRoute: typeof PublicSocietiesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/events': {
      id: '/_public/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof PublicEventsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/events/new': {
      id: '/admin/events/new'
      path: '/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AdminEventsNewRouteImport
      parentRoute: typeof AdminEventsRoute
    }
    '/admin/events/$eventId': {
      id: '/admin/events/$eventId'
      path: '/$eventId'
      fullPath: '/admin/events/$eventId'
      preLoaderRoute: typeof AdminEventsEventIdRouteImport
      parentRoute: typeof AdminEventsRoute
    }
    '/admin/check-in/$eventId': {
      id: '/admin/check-in/$eventId'
      path: '/$eventId'
      fullPath: '/admin/check-in/$eventId'
      preLoaderRoute: typeof AdminCheckInEventIdRouteImport
      parentRoute: typeof AdminCheckInRoute
    }
    '/_public/societies/$slug': {
      id: '/_public/societies/$slug'
      path: '/$slug'
      fullPath: '/societies/$slug'
      preLoaderRoute: typeof PublicSocietiesSlugRouteImport
      parentRoute: typeof PublicSocietiesRoute
    }
    '/_public/events/$eventId': {
      id: '/_public/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof PublicEventsEventIdRouteImport
      parentRoute: typeof PublicEventsRoute
    }
    '/admin/events/$eventId/edit': {
      id: '/admin/events/$eventId/edit'
      path: '/edit'
      fullPath: '/admin/events/$eventId/edit'
      preLoaderRoute: typeof AdminEventsEventIdEditRouteImport
      parentRoute: typeof AdminEventsEventIdRoute
    }
  }
}

interface PublicEventsRouteChildren {
  PublicEventsEventIdRoute: typeof PublicEventsEventIdRoute
}

const PublicEventsRouteChildren: PublicEventsRouteChildren = {
  PublicEventsEventIdRoute: PublicEventsEventIdRoute,
}

const PublicEventsRouteWithChildren = PublicEventsRoute._addFileChildren(
  PublicEventsRouteChildren,
)

interface PublicSocietiesRouteChildren {
  PublicSocietiesSlugRoute: typeof PublicSocietiesSlugRoute
}

const PublicSocietiesRouteChildren: PublicSocietiesRouteChildren = {
  PublicSocietiesSlugRoute: PublicSocietiesSlugRoute,
}

const PublicSocietiesRouteWithChildren = PublicSocietiesRoute._addFileChildren(
  PublicSocietiesRouteChildren,
)

interface PublicRouteChildren {
  PublicEventsRoute: typeof PublicEventsRouteWithChildren
  PublicSocietiesRoute: typeof PublicSocietiesRouteWithChildren
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicEventsRoute: PublicEventsRouteWithChildren,
  PublicSocietiesRoute: PublicSocietiesRouteWithChildren,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminCheckInRouteChildren {
  AdminCheckInEventIdRoute: typeof AdminCheckInEventIdRoute
}

const AdminCheckInRouteChildren: AdminCheckInRouteChildren = {
  AdminCheckInEventIdRoute: AdminCheckInEventIdRoute,
}

const AdminCheckInRouteWithChildren = AdminCheckInRoute._addFileChildren(
  AdminCheckInRouteChildren,
)

interface AdminEventsEventIdRouteChildren {
  AdminEventsEventIdEditRoute: typeof AdminEventsEventIdEditRoute
}

const AdminEventsEventIdRouteChildren: AdminEventsEventIdRouteChildren = {
  AdminEventsEventIdEditRoute: AdminEventsEventIdEditRoute,
}

const AdminEventsEventIdRouteWithChildren =
  AdminEventsEventIdRoute._addFileChildren(AdminEventsEventIdRouteChildren)

interface AdminEventsRouteChildren {
  AdminEventsEventIdRoute: typeof AdminEventsEventIdRouteWithChildren
  AdminEventsNewRoute: typeof AdminEventsNewRoute
}

const AdminEventsRouteChildren: AdminEventsRouteChildren = {
  AdminEventsEventIdRoute: AdminEventsEventIdRouteWithChildren,
  AdminEventsNewRoute: AdminEventsNewRoute,
}

const AdminEventsRouteWithChildren = AdminEventsRoute._addFileChildren(
  AdminEventsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminLayoutRoute: AdminLayoutRoute,
  AdminCheckInRoute: AdminCheckInRouteWithChildren,
  AdminEventsRoute: AdminEventsRouteWithChildren,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
  AdminSocietiesRoute: AdminSocietiesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
