// PocketBase auto-generated types dummy file
// This file is generated by PocketBase when running locally.
// Creating this dummy file to satisfy local IDE type checking.
declare const $app: any;
declare const $apis: any;
declare const $os: any;
declare const $security: any;
declare function onRecordUpdateRequest(handler: (e: any) => void, collection: string): void;
declare function onRecordCreateRequest(handler: (e: any) => void, collection: string): void;
