import { index, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  route("healthz", "routes/healthz.ts"),
  route("robots.txt", "routes/robots.ts"),
  route("sitemap.xml", "routes/sitemap.ts"),
  index("routes/index.tsx"),
  route("events", "routes/events.tsx"),
  route("events/:slug", "routes/events.$slug.tsx"),
  route("blog", "routes/blog.index.tsx"),
  route("blog/:slug", "routes/blog.$slug.tsx"),
  route("societies", "routes/societies.tsx"),
  route("societies/wie", "routes/societies_.wie.tsx"),
  route("societies/:slug", "routes/societies_.$slug.tsx"),
  route("full-execom", "routes/full-execom.tsx"),
  route("staging-login", "routes/staging-login.tsx"),
  route("terms-and-conditions", "routes/terms-and-conditions.tsx"),
  route("privacy-policy", "routes/privacy-policy.tsx"),
  route("refund-and-cancellation-policy", "routes/refund-and-cancellation-policy.tsx"),
  route("register/:eventId", "routes/register.$eventId.tsx"),
  route("payment/:registrationId", "routes/payment.$registrationId.tsx"),
  route("ticket/:ticketId/qr.png", "routes/ticket-qr.$ticketId.ts"),
  route("ticket/:ticketId", "routes/ticket.$ticketId.tsx"),
  route("c/:token/certificate.png", "routes/certificate-png.$token.ts"),
  route("c/:token/certificate.pdf", "routes/certificate-pdf.$token.ts"),
  route("c/:token", "routes/c.$token.tsx"),

  route("FIFA", "routes/FIFA/index.tsx"),
  route("FIFA/dashboard", "routes/FIFA/dashboard.tsx"),
  route("FIFA/leaderboard", "routes/FIFA/leaderboard.tsx"),
  route("FIFA/matches", "routes/FIFA/matches.tsx"),
  route("FIFA/matches/:id", "routes/FIFA/matches.$id.tsx"),
  route("FIFA/rules", "routes/FIFA/rules.tsx"),

  route("admin", "routes/admin.tsx", [
    index("routes/admin.index.tsx"),
    route("dashboard", "routes/admin.dashboard.tsx"),
    route("events", "routes/admin.events.index.tsx"),
    route("events/new", "routes/admin.events.new.tsx"),
    route("events/:id", "routes/admin.events.$id.tsx"),
    route("events/:id/edit", "routes/admin.events.$id.edit.tsx"),
    route("registrations", "routes/admin.registrations.index.tsx"),
    route("payments", "routes/admin.payments.tsx"),
    route("registrations/:id", "routes/admin.registrations.$id.tsx"),
    route("societies", "routes/admin.societies.index.tsx"),
    route("societies/new", "routes/admin.societies.new.tsx"),
    route("societies/:id/edit", "routes/admin.societies.$id.edit.tsx"),
    route("execom", "routes/admin.execom.index.tsx"),
    route("execom/new", "routes/admin.execom.new.tsx"),
    route("execom/:id/edit", "routes/admin.execom.$id.edit.tsx"),
    route("blogs", "routes/admin.blogs.tsx"),
    route("users", "routes/admin.users.tsx"),
    route("access", "routes/admin.access.tsx"),
    route("check-in", "routes/admin.check-in.tsx"),
    route("data-health", "routes/admin.data-health.tsx"),
    route("FIFA/matches", "routes/admin.FIFA.matches.tsx"),
    route("FIFA/matches/:id", "routes/admin.FIFA.matches.$id.tsx"),
    route("FIFA/raffle", "routes/admin.FIFA.raffle.tsx"),
    route("FIFA/settings", "routes/admin.FIFA.settings.tsx"),
  ]),
] satisfies RouteConfig;
