/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SocietiesRouteImport } from './routes/societies'
import { Route as FullExecomRouteImport } from './routes/full-execom'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as FIFAIndexRouteImport } from './routes/FIFA/index'
import { Route as TicketTicketIdRouteImport } from './routes/ticket.$ticketId'
import { Route as RegisterEventIdRouteImport } from './routes/register.$eventId'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiRegistrationsRouteImport } from './routes/api/registrations'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCheckInRouteImport } from './routes/admin.check-in'
import { Route as AdminBlogsRouteImport } from './routes/admin.blogs'
import { Route as FIFARulesRouteImport } from './routes/FIFA/rules'
import { Route as FIFAMatchesRouteImport } from './routes/FIFA/matches'
import { Route as FIFALeaderboardRouteImport } from './routes/FIFA/leaderboard'
import { Route as FIFAFeedRouteImport } from './routes/FIFA/feed'
import { Route as FIFADashboardRouteImport } from './routes/FIFA/dashboard'
import { Route as AdminSocietiesIndexRouteImport } from './routes/admin.societies.index'
import { Route as AdminRegistrationsIndexRouteImport } from './routes/admin.registrations.index'
import { Route as AdminExecomIndexRouteImport } from './routes/admin.execom.index'
import { Route as AdminEventsIndexRouteImport } from './routes/admin.events.index'
import { Route as ApiTicketTicketIdRouteImport } from './routes/api/ticket.$ticketId'
import { Route as ApiSocietySlugRouteImport } from './routes/api/society.$slug'
import { Route as ApiFilesSplatRouteImport } from './routes/api/files.$'
import { Route as ApiFifaMatchesRouteImport } from './routes/api/fifa/matches'
import { Route as ApiFifaLiveScoresRouteImport } from './routes/api/fifa/live-scores'
import { Route as ApiFifaDashboardRouteImport } from './routes/api/fifa/dashboard'
import { Route as ApiFifaBetsRouteImport } from './routes/api/fifa/bets'
import { Route as ApiEventsValidateCouponRouteImport } from './routes/api/events.validate-coupon'
import { Route as ApiEventsIdRouteImport } from './routes/api/events.$id'
import { Route as ApiCheckInVerifyRouteImport } from './routes/api/check-in.verify'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthInitRouteImport } from './routes/api/auth/init'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminStatsRouteImport } from './routes/api/admin/stats'
import { Route as ApiAdminSocietiesRouteImport } from './routes/api/admin/societies'
import { Route as ApiAdminRegistrationsRouteImport } from './routes/api/admin/registrations'
import { Route as ApiAdminExecomRouteImport } from './routes/api/admin/execom'
import { Route as ApiAdminEventsRouteImport } from './routes/api/admin/events'
import { Route as AdminSocietiesNewRouteImport } from './routes/admin.societies.new'
import { Route as AdminRegistrationsIdRouteImport } from './routes/admin.registrations.$id'
import { Route as AdminExecomNewRouteImport } from './routes/admin.execom.new'
import { Route as AdminEventsNewRouteImport } from './routes/admin.events.new'
import { Route as AdminFIFATestingRouteImport } from './routes/admin.FIFA.testing'
import { Route as AdminFIFASettingsRouteImport } from './routes/admin.FIFA.settings'
import { Route as AdminFIFARaffleRouteImport } from './routes/admin.FIFA.raffle'
import { Route as FIFAMatchesIdRouteImport } from './routes/FIFA/matches.$id'
import { Route as AdminFIFAMatchesIndexRouteImport } from './routes/admin.FIFA.matches.index'
import { Route as ApiEventsIdExportRouteImport } from './routes/api/events.$id.export'
import { Route as ApiAuthCallbackGoogleRouteImport } from './routes/api/auth/callback/google'
import { Route as ApiAdminSocietiesIdRouteImport } from './routes/api/admin/societies.$id'
import { Route as ApiAdminRegistrationsIdRouteImport } from './routes/api/admin/registrations.$id'
import { Route as ApiAdminFifaTestingRouteImport } from './routes/api/admin/fifa/testing'
import { Route as ApiAdminFifaSettleRouteImport } from './routes/api/admin/fifa/settle'
import { Route as ApiAdminFifaSettingsRouteImport } from './routes/api/admin/fifa/settings'
import { Route as ApiAdminFifaRaffleDrawsRouteImport } from './routes/api/admin/fifa/raffle-draws'
import { Route as ApiAdminFifaRaffleRouteImport } from './routes/api/admin/fifa/raffle'
import { Route as ApiAdminFifaMatchesRouteImport } from './routes/api/admin/fifa/matches'
import { Route as ApiAdminFifaMarketsRouteImport } from './routes/api/admin/fifa/markets'
import { Route as ApiAdminFifaBetsRouteImport } from './routes/api/admin/fifa/bets'
import { Route as ApiAdminExecomIdRouteImport } from './routes/api/admin/execom.$id'
import { Route as ApiAdminEventsIdRouteImport } from './routes/api/admin/events.$id'
import { Route as AdminSocietiesIdEditRouteImport } from './routes/admin.societies.$id.edit'
import { Route as AdminExecomIdEditRouteImport } from './routes/admin.execom.$id.edit'
import { Route as AdminEventsIdEditRouteImport } from './routes/admin.events.$id.edit'
import { Route as AdminFIFAMatchesIdRouteImport } from './routes/admin.FIFA.matches.$id'
import { Route as ApiAdminFifaMatchesIdRouteImport } from './routes/api/admin/fifa/matches.$id'
import { Route as ApiAdminFifaMarketsIdRouteImport } from './routes/api/admin/fifa/markets.$id'
import { Route as ApiAdminEventsIdRegistrationsCsvRouteImport } from './routes/api/admin.events.$id.registrations-csv'
import { Route as ApiAdminEventsIdCouponsRouteImport } from './routes/api/admin/events.$id.coupons'

const SocietiesRoute = SocietiesRouteImport.update({
  id: '/societies',
  path: '/societies',
  getParentRoute: () => rootRouteImport,
} as any)
const FullExecomRoute = FullExecomRouteImport.update({
  id: '/full-execom',
  path: '/full-execom',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const FIFAIndexRoute = FIFAIndexRouteImport.update({
  id: '/FIFA/',
  path: '/FIFA/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketTicketIdRoute = TicketTicketIdRouteImport.update({
  id: '/ticket/$ticketId',
  path: '/ticket/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterEventIdRoute = RegisterEventIdRouteImport.update({
  id: '/register/$eventId',
  path: '/register/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegistrationsRoute = ApiRegistrationsRouteImport.update({
  id: '/api/registrations',
  path: '/api/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCheckInRoute = AdminCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminRoute,
} as any)
const FIFARulesRoute = FIFARulesRouteImport.update({
  id: '/FIFA/rules',
  path: '/FIFA/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const FIFAMatchesRoute = FIFAMatchesRouteImport.update({
  id: '/FIFA/matches',
  path: '/FIFA/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const FIFALeaderboardRoute = FIFALeaderboardRouteImport.update({
  id: '/FIFA/leaderboard',
  path: '/FIFA/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FIFAFeedRoute = FIFAFeedRouteImport.update({
  id: '/FIFA/feed',
  path: '/FIFA/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const FIFADashboardRoute = FIFADashboardRouteImport.update({
  id: '/FIFA/dashboard',
  path: '/FIFA/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSocietiesIndexRoute = AdminSocietiesIndexRouteImport.update({
  id: '/societies/',
  path: '/societies/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegistrationsIndexRoute = AdminRegistrationsIndexRouteImport.update({
  id: '/registrations/',
  path: '/registrations/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExecomIndexRoute = AdminExecomIndexRouteImport.update({
  id: '/execom/',
  path: '/execom/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiTicketTicketIdRoute = ApiTicketTicketIdRouteImport.update({
  id: '/api/ticket/$ticketId',
  path: '/api/ticket/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSocietySlugRoute = ApiSocietySlugRouteImport.update({
  id: '/api/society/$slug',
  path: '/api/society/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesSplatRoute = ApiFilesSplatRouteImport.update({
  id: '/api/files/$',
  path: '/api/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFifaMatchesRoute = ApiFifaMatchesRouteImport.update({
  id: '/api/fifa/matches',
  path: '/api/fifa/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFifaLiveScoresRoute = ApiFifaLiveScoresRouteImport.update({
  id: '/api/fifa/live-scores',
  path: '/api/fifa/live-scores',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFifaDashboardRoute = ApiFifaDashboardRouteImport.update({
  id: '/api/fifa/dashboard',
  path: '/api/fifa/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFifaBetsRoute = ApiFifaBetsRouteImport.update({
  id: '/api/fifa/bets',
  path: '/api/fifa/bets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsValidateCouponRoute = ApiEventsValidateCouponRouteImport.update({
  id: '/api/events/validate-coupon',
  path: '/api/events/validate-coupon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsIdRoute = ApiEventsIdRouteImport.update({
  id: '/api/events/$id',
  path: '/api/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckInVerifyRoute = ApiCheckInVerifyRouteImport.update({
  id: '/api/check-in/verify',
  path: '/api/check-in/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthInitRoute = ApiAuthInitRouteImport.update({
  id: '/api/auth/init',
  path: '/api/auth/init',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatsRoute = ApiAdminStatsRouteImport.update({
  id: '/api/admin/stats',
  path: '/api/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSocietiesRoute = ApiAdminSocietiesRouteImport.update({
  id: '/api/admin/societies',
  path: '/api/admin/societies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRegistrationsRoute = ApiAdminRegistrationsRouteImport.update({
  id: '/api/admin/registrations',
  path: '/api/admin/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminExecomRoute = ApiAdminExecomRouteImport.update({
  id: '/api/admin/execom',
  path: '/api/admin/execom',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminEventsRoute = ApiAdminEventsRouteImport.update({
  id: '/api/admin/events',
  path: '/api/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSocietiesNewRoute = AdminSocietiesNewRouteImport.update({
  id: '/societies/new',
  path: '/societies/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegistrationsIdRoute = AdminRegistrationsIdRouteImport.update({
  id: '/registrations/$id',
  path: '/registrations/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExecomNewRoute = AdminExecomNewRouteImport.update({
  id: '/execom/new',
  path: '/execom/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsNewRoute = AdminEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFIFATestingRoute = AdminFIFATestingRouteImport.update({
  id: '/FIFA/testing',
  path: '/FIFA/testing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFIFASettingsRoute = AdminFIFASettingsRouteImport.update({
  id: '/FIFA/settings',
  path: '/FIFA/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFIFARaffleRoute = AdminFIFARaffleRouteImport.update({
  id: '/FIFA/raffle',
  path: '/FIFA/raffle',
  getParentRoute: () => AdminRoute,
} as any)
const FIFAMatchesIdRoute = FIFAMatchesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FIFAMatchesRoute,
} as any)
const AdminFIFAMatchesIndexRoute = AdminFIFAMatchesIndexRouteImport.update({
  id: '/FIFA/matches/',
  path: '/FIFA/matches/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiEventsIdExportRoute = ApiEventsIdExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ApiEventsIdRoute,
} as any)
const ApiAuthCallbackGoogleRoute = ApiAuthCallbackGoogleRouteImport.update({
  id: '/api/auth/callback/google',
  path: '/api/auth/callback/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSocietiesIdRoute = ApiAdminSocietiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminSocietiesRoute,
} as any)
const ApiAdminRegistrationsIdRoute = ApiAdminRegistrationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminRegistrationsRoute,
} as any)
const ApiAdminFifaTestingRoute = ApiAdminFifaTestingRouteImport.update({
  id: '/api/admin/fifa/testing',
  path: '/api/admin/fifa/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminFifaSettleRoute = ApiAdminFifaSettleRouteImport.update({
  id: '/api/admin/fifa/settle',
  path: '/api/admin/fifa/settle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminFifaSettingsRoute = ApiAdminFifaSettingsRouteImport.update({
  id: '/api/admin/fifa/settings',
  path: '/api/admin/fifa/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminFifaRaffleDrawsRoute = ApiAdminFifaRaffleDrawsRouteImport.update({
  id: '/api/admin/fifa/raffle-draws',
  path: '/api/admin/fifa/raffle-draws',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminFifaRaffleRoute = ApiAdminFifaRaffleRouteImport.update({
  id: '/api/admin/fifa/raffle',
  path: '/api/admin/fifa/raffle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminFifaMatchesRoute = ApiAdminFifaMatchesRouteImport.update({
  id: '/api/admin/fifa/matches',
  path: '/api/admin/fifa/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminFifaMarketsRoute = ApiAdminFifaMarketsRouteImport.update({
  id: '/api/admin/fifa/markets',
  path: '/api/admin/fifa/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminFifaBetsRoute = ApiAdminFifaBetsRouteImport.update({
  id: '/api/admin/fifa/bets',
  path: '/api/admin/fifa/bets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminExecomIdRoute = ApiAdminExecomIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminExecomRoute,
} as any)
const ApiAdminEventsIdRoute = ApiAdminEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminEventsRoute,
} as any)
const AdminSocietiesIdEditRoute = AdminSocietiesIdEditRouteImport.update({
  id: '/societies/$id/edit',
  path: '/societies/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExecomIdEditRoute = AdminExecomIdEditRouteImport.update({
  id: '/execom/$id/edit',
  path: '/execom/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsIdEditRoute = AdminEventsIdEditRouteImport.update({
  id: '/events/$id/edit',
  path: '/events/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFIFAMatchesIdRoute = AdminFIFAMatchesIdRouteImport.update({
  id: '/FIFA/matches/$id',
  path: '/FIFA/matches/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminFifaMatchesIdRoute = ApiAdminFifaMatchesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminFifaMatchesRoute,
} as any)
const ApiAdminFifaMarketsIdRoute = ApiAdminFifaMarketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminFifaMarketsRoute,
} as any)
const ApiAdminEventsIdRegistrationsCsvRoute =
  ApiAdminEventsIdRegistrationsCsvRouteImport.update({
    id: '/registrations-csv',
    path: '/registrations-csv',
    getParentRoute: () => ApiAdminEventsIdRoute,
  } as any)
const ApiAdminEventsIdCouponsRoute = ApiAdminEventsIdCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => ApiAdminEventsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/events': typeof EventsRoute
  '/full-execom': typeof FullExecomRoute
  '/societies': typeof SocietiesRoute
  '/FIFA/dashboard': typeof FIFADashboardRoute
  '/FIFA/feed': typeof FIFAFeedRoute
  '/FIFA/leaderboard': typeof FIFALeaderboardRoute
  '/FIFA/matches': typeof FIFAMatchesRouteWithChildren
  '/FIFA/rules': typeof FIFARulesRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/check-in': typeof AdminCheckInRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/registrations': typeof ApiRegistrationsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/register/$eventId': typeof RegisterEventIdRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
  '/FIFA/': typeof FIFAIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/FIFA/matches/$id': typeof FIFAMatchesIdRoute
  '/admin/FIFA/raffle': typeof AdminFIFARaffleRoute
  '/admin/FIFA/settings': typeof AdminFIFASettingsRoute
  '/admin/FIFA/testing': typeof AdminFIFATestingRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/execom/new': typeof AdminExecomNewRoute
  '/admin/registrations/$id': typeof AdminRegistrationsIdRoute
  '/admin/societies/new': typeof AdminSocietiesNewRoute
  '/api/admin/events': typeof ApiAdminEventsRouteWithChildren
  '/api/admin/execom': typeof ApiAdminExecomRouteWithChildren
  '/api/admin/registrations': typeof ApiAdminRegistrationsRouteWithChildren
  '/api/admin/societies': typeof ApiAdminSocietiesRouteWithChildren
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/init': typeof ApiAuthInitRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/check-in/verify': typeof ApiCheckInVerifyRoute
  '/api/events/$id': typeof ApiEventsIdRouteWithChildren
  '/api/events/validate-coupon': typeof ApiEventsValidateCouponRoute
  '/api/fifa/bets': typeof ApiFifaBetsRoute
  '/api/fifa/dashboard': typeof ApiFifaDashboardRoute
  '/api/fifa/live-scores': typeof ApiFifaLiveScoresRoute
  '/api/fifa/matches': typeof ApiFifaMatchesRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/society/$slug': typeof ApiSocietySlugRoute
  '/api/ticket/$ticketId': typeof ApiTicketTicketIdRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/execom/': typeof AdminExecomIndexRoute
  '/admin/registrations/': typeof AdminRegistrationsIndexRoute
  '/admin/societies/': typeof AdminSocietiesIndexRoute
  '/admin/FIFA/matches/$id': typeof AdminFIFAMatchesIdRoute
  '/admin/events/$id/edit': typeof AdminEventsIdEditRoute
  '/admin/execom/$id/edit': typeof AdminExecomIdEditRoute
  '/admin/societies/$id/edit': typeof AdminSocietiesIdEditRoute
  '/api/admin/events/$id': typeof ApiAdminEventsIdRouteWithChildren
  '/api/admin/execom/$id': typeof ApiAdminExecomIdRoute
  '/api/admin/fifa/bets': typeof ApiAdminFifaBetsRoute
  '/api/admin/fifa/markets': typeof ApiAdminFifaMarketsRouteWithChildren
  '/api/admin/fifa/matches': typeof ApiAdminFifaMatchesRouteWithChildren
  '/api/admin/fifa/raffle': typeof ApiAdminFifaRaffleRoute
  '/api/admin/fifa/raffle-draws': typeof ApiAdminFifaRaffleDrawsRoute
  '/api/admin/fifa/settings': typeof ApiAdminFifaSettingsRoute
  '/api/admin/fifa/settle': typeof ApiAdminFifaSettleRoute
  '/api/admin/fifa/testing': typeof ApiAdminFifaTestingRoute
  '/api/admin/registrations/$id': typeof ApiAdminRegistrationsIdRoute
  '/api/admin/societies/$id': typeof ApiAdminSocietiesIdRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/api/events/$id/export': typeof ApiEventsIdExportRoute
  '/admin/FIFA/matches/': typeof AdminFIFAMatchesIndexRoute
  '/api/admin/events/$id/coupons': typeof ApiAdminEventsIdCouponsRoute
  '/api/admin/events/$id/registrations-csv': typeof ApiAdminEventsIdRegistrationsCsvRoute
  '/api/admin/fifa/markets/$id': typeof ApiAdminFifaMarketsIdRoute
  '/api/admin/fifa/matches/$id': typeof ApiAdminFifaMatchesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/events': typeof EventsRoute
  '/full-execom': typeof FullExecomRoute
  '/societies': typeof SocietiesRoute
  '/FIFA/dashboard': typeof FIFADashboardRoute
  '/FIFA/feed': typeof FIFAFeedRoute
  '/FIFA/leaderboard': typeof FIFALeaderboardRoute
  '/FIFA/matches': typeof FIFAMatchesRouteWithChildren
  '/FIFA/rules': typeof FIFARulesRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/check-in': typeof AdminCheckInRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/registrations': typeof ApiRegistrationsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/register/$eventId': typeof RegisterEventIdRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
  '/FIFA': typeof FIFAIndexRoute
  '/blog': typeof BlogIndexRoute
  '/FIFA/matches/$id': typeof FIFAMatchesIdRoute
  '/admin/FIFA/raffle': typeof AdminFIFARaffleRoute
  '/admin/FIFA/settings': typeof AdminFIFASettingsRoute
  '/admin/FIFA/testing': typeof AdminFIFATestingRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/execom/new': typeof AdminExecomNewRoute
  '/admin/registrations/$id': typeof AdminRegistrationsIdRoute
  '/admin/societies/new': typeof AdminSocietiesNewRoute
  '/api/admin/events': typeof ApiAdminEventsRouteWithChildren
  '/api/admin/execom': typeof ApiAdminExecomRouteWithChildren
  '/api/admin/registrations': typeof ApiAdminRegistrationsRouteWithChildren
  '/api/admin/societies': typeof ApiAdminSocietiesRouteWithChildren
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/init': typeof ApiAuthInitRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/check-in/verify': typeof ApiCheckInVerifyRoute
  '/api/events/$id': typeof ApiEventsIdRouteWithChildren
  '/api/events/validate-coupon': typeof ApiEventsValidateCouponRoute
  '/api/fifa/bets': typeof ApiFifaBetsRoute
  '/api/fifa/dashboard': typeof ApiFifaDashboardRoute
  '/api/fifa/live-scores': typeof ApiFifaLiveScoresRoute
  '/api/fifa/matches': typeof ApiFifaMatchesRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/society/$slug': typeof ApiSocietySlugRoute
  '/api/ticket/$ticketId': typeof ApiTicketTicketIdRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/admin/execom': typeof AdminExecomIndexRoute
  '/admin/registrations': typeof AdminRegistrationsIndexRoute
  '/admin/societies': typeof AdminSocietiesIndexRoute
  '/admin/FIFA/matches/$id': typeof AdminFIFAMatchesIdRoute
  '/admin/events/$id/edit': typeof AdminEventsIdEditRoute
  '/admin/execom/$id/edit': typeof AdminExecomIdEditRoute
  '/admin/societies/$id/edit': typeof AdminSocietiesIdEditRoute
  '/api/admin/events/$id': typeof ApiAdminEventsIdRouteWithChildren
  '/api/admin/execom/$id': typeof ApiAdminExecomIdRoute
  '/api/admin/fifa/bets': typeof ApiAdminFifaBetsRoute
  '/api/admin/fifa/markets': typeof ApiAdminFifaMarketsRouteWithChildren
  '/api/admin/fifa/matches': typeof ApiAdminFifaMatchesRouteWithChildren
  '/api/admin/fifa/raffle': typeof ApiAdminFifaRaffleRoute
  '/api/admin/fifa/raffle-draws': typeof ApiAdminFifaRaffleDrawsRoute
  '/api/admin/fifa/settings': typeof ApiAdminFifaSettingsRoute
  '/api/admin/fifa/settle': typeof ApiAdminFifaSettleRoute
  '/api/admin/fifa/testing': typeof ApiAdminFifaTestingRoute
  '/api/admin/registrations/$id': typeof ApiAdminRegistrationsIdRoute
  '/api/admin/societies/$id': typeof ApiAdminSocietiesIdRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/api/events/$id/export': typeof ApiEventsIdExportRoute
  '/admin/FIFA/matches': typeof AdminFIFAMatchesIndexRoute
  '/api/admin/events/$id/coupons': typeof ApiAdminEventsIdCouponsRoute
  '/api/admin/events/$id/registrations-csv': typeof ApiAdminEventsIdRegistrationsCsvRoute
  '/api/admin/fifa/markets/$id': typeof ApiAdminFifaMarketsIdRoute
  '/api/admin/fifa/matches/$id': typeof ApiAdminFifaMatchesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/events': typeof EventsRoute
  '/full-execom': typeof FullExecomRoute
  '/societies': typeof SocietiesRoute
  '/FIFA/dashboard': typeof FIFADashboardRoute
  '/FIFA/feed': typeof FIFAFeedRoute
  '/FIFA/leaderboard': typeof FIFALeaderboardRoute
  '/FIFA/matches': typeof FIFAMatchesRouteWithChildren
  '/FIFA/rules': typeof FIFARulesRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/check-in': typeof AdminCheckInRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/registrations': typeof ApiRegistrationsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/register/$eventId': typeof RegisterEventIdRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
  '/FIFA/': typeof FIFAIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/FIFA/matches/$id': typeof FIFAMatchesIdRoute
  '/admin/FIFA/raffle': typeof AdminFIFARaffleRoute
  '/admin/FIFA/settings': typeof AdminFIFASettingsRoute
  '/admin/FIFA/testing': typeof AdminFIFATestingRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/execom/new': typeof AdminExecomNewRoute
  '/admin/registrations/$id': typeof AdminRegistrationsIdRoute
  '/admin/societies/new': typeof AdminSocietiesNewRoute
  '/api/admin/events': typeof ApiAdminEventsRouteWithChildren
  '/api/admin/execom': typeof ApiAdminExecomRouteWithChildren
  '/api/admin/registrations': typeof ApiAdminRegistrationsRouteWithChildren
  '/api/admin/societies': typeof ApiAdminSocietiesRouteWithChildren
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/init': typeof ApiAuthInitRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/check-in/verify': typeof ApiCheckInVerifyRoute
  '/api/events/$id': typeof ApiEventsIdRouteWithChildren
  '/api/events/validate-coupon': typeof ApiEventsValidateCouponRoute
  '/api/fifa/bets': typeof ApiFifaBetsRoute
  '/api/fifa/dashboard': typeof ApiFifaDashboardRoute
  '/api/fifa/live-scores': typeof ApiFifaLiveScoresRoute
  '/api/fifa/matches': typeof ApiFifaMatchesRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/society/$slug': typeof ApiSocietySlugRoute
  '/api/ticket/$ticketId': typeof ApiTicketTicketIdRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/execom/': typeof AdminExecomIndexRoute
  '/admin/registrations/': typeof AdminRegistrationsIndexRoute
  '/admin/societies/': typeof AdminSocietiesIndexRoute
  '/admin/FIFA/matches/$id': typeof AdminFIFAMatchesIdRoute
  '/admin/events/$id/edit': typeof AdminEventsIdEditRoute
  '/admin/execom/$id/edit': typeof AdminExecomIdEditRoute
  '/admin/societies/$id/edit': typeof AdminSocietiesIdEditRoute
  '/api/admin/events/$id': typeof ApiAdminEventsIdRouteWithChildren
  '/api/admin/execom/$id': typeof ApiAdminExecomIdRoute
  '/api/admin/fifa/bets': typeof ApiAdminFifaBetsRoute
  '/api/admin/fifa/markets': typeof ApiAdminFifaMarketsRouteWithChildren
  '/api/admin/fifa/matches': typeof ApiAdminFifaMatchesRouteWithChildren
  '/api/admin/fifa/raffle': typeof ApiAdminFifaRaffleRoute
  '/api/admin/fifa/raffle-draws': typeof ApiAdminFifaRaffleDrawsRoute
  '/api/admin/fifa/settings': typeof ApiAdminFifaSettingsRoute
  '/api/admin/fifa/settle': typeof ApiAdminFifaSettleRoute
  '/api/admin/fifa/testing': typeof ApiAdminFifaTestingRoute
  '/api/admin/registrations/$id': typeof ApiAdminRegistrationsIdRoute
  '/api/admin/societies/$id': typeof ApiAdminSocietiesIdRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/api/events/$id/export': typeof ApiEventsIdExportRoute
  '/admin/FIFA/matches/': typeof AdminFIFAMatchesIndexRoute
  '/api/admin/events/$id/coupons': typeof ApiAdminEventsIdCouponsRoute
  '/api/admin/events/$id/registrations-csv': typeof ApiAdminEventsIdRegistrationsCsvRoute
  '/api/admin/fifa/markets/$id': typeof ApiAdminFifaMarketsIdRoute
  '/api/admin/fifa/matches/$id': typeof ApiAdminFifaMatchesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/events'
    | '/full-execom'
    | '/societies'
    | '/FIFA/dashboard'
    | '/FIFA/feed'
    | '/FIFA/leaderboard'
    | '/FIFA/matches'
    | '/FIFA/rules'
    | '/admin/blogs'
    | '/admin/check-in'
    | '/admin/dashboard'
    | '/admin/users'
    | '/api/registrations'
    | '/blog/$slug'
    | '/register/$eventId'
    | '/ticket/$ticketId'
    | '/FIFA/'
    | '/blog/'
    | '/FIFA/matches/$id'
    | '/admin/FIFA/raffle'
    | '/admin/FIFA/settings'
    | '/admin/FIFA/testing'
    | '/admin/events/new'
    | '/admin/execom/new'
    | '/admin/registrations/$id'
    | '/admin/societies/new'
    | '/api/admin/events'
    | '/api/admin/execom'
    | '/api/admin/registrations'
    | '/api/admin/societies'
    | '/api/admin/stats'
    | '/api/admin/users'
    | '/api/auth/init'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/check-in/verify'
    | '/api/events/$id'
    | '/api/events/validate-coupon'
    | '/api/fifa/bets'
    | '/api/fifa/dashboard'
    | '/api/fifa/live-scores'
    | '/api/fifa/matches'
    | '/api/files/$'
    | '/api/society/$slug'
    | '/api/ticket/$ticketId'
    | '/admin/events/'
    | '/admin/execom/'
    | '/admin/registrations/'
    | '/admin/societies/'
    | '/admin/FIFA/matches/$id'
    | '/admin/events/$id/edit'
    | '/admin/execom/$id/edit'
    | '/admin/societies/$id/edit'
    | '/api/admin/events/$id'
    | '/api/admin/execom/$id'
    | '/api/admin/fifa/bets'
    | '/api/admin/fifa/markets'
    | '/api/admin/fifa/matches'
    | '/api/admin/fifa/raffle'
    | '/api/admin/fifa/raffle-draws'
    | '/api/admin/fifa/settings'
    | '/api/admin/fifa/settle'
    | '/api/admin/fifa/testing'
    | '/api/admin/registrations/$id'
    | '/api/admin/societies/$id'
    | '/api/auth/callback/google'
    | '/api/events/$id/export'
    | '/admin/FIFA/matches/'
    | '/api/admin/events/$id/coupons'
    | '/api/admin/events/$id/registrations-csv'
    | '/api/admin/fifa/markets/$id'
    | '/api/admin/fifa/matches/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/events'
    | '/full-execom'
    | '/societies'
    | '/FIFA/dashboard'
    | '/FIFA/feed'
    | '/FIFA/leaderboard'
    | '/FIFA/matches'
    | '/FIFA/rules'
    | '/admin/blogs'
    | '/admin/check-in'
    | '/admin/dashboard'
    | '/admin/users'
    | '/api/registrations'
    | '/blog/$slug'
    | '/register/$eventId'
    | '/ticket/$ticketId'
    | '/FIFA'
    | '/blog'
    | '/FIFA/matches/$id'
    | '/admin/FIFA/raffle'
    | '/admin/FIFA/settings'
    | '/admin/FIFA/testing'
    | '/admin/events/new'
    | '/admin/execom/new'
    | '/admin/registrations/$id'
    | '/admin/societies/new'
    | '/api/admin/events'
    | '/api/admin/execom'
    | '/api/admin/registrations'
    | '/api/admin/societies'
    | '/api/admin/stats'
    | '/api/admin/users'
    | '/api/auth/init'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/check-in/verify'
    | '/api/events/$id'
    | '/api/events/validate-coupon'
    | '/api/fifa/bets'
    | '/api/fifa/dashboard'
    | '/api/fifa/live-scores'
    | '/api/fifa/matches'
    | '/api/files/$'
    | '/api/society/$slug'
    | '/api/ticket/$ticketId'
    | '/admin/events'
    | '/admin/execom'
    | '/admin/registrations'
    | '/admin/societies'
    | '/admin/FIFA/matches/$id'
    | '/admin/events/$id/edit'
    | '/admin/execom/$id/edit'
    | '/admin/societies/$id/edit'
    | '/api/admin/events/$id'
    | '/api/admin/execom/$id'
    | '/api/admin/fifa/bets'
    | '/api/admin/fifa/markets'
    | '/api/admin/fifa/matches'
    | '/api/admin/fifa/raffle'
    | '/api/admin/fifa/raffle-draws'
    | '/api/admin/fifa/settings'
    | '/api/admin/fifa/settle'
    | '/api/admin/fifa/testing'
    | '/api/admin/registrations/$id'
    | '/api/admin/societies/$id'
    | '/api/auth/callback/google'
    | '/api/events/$id/export'
    | '/admin/FIFA/matches'
    | '/api/admin/events/$id/coupons'
    | '/api/admin/events/$id/registrations-csv'
    | '/api/admin/fifa/markets/$id'
    | '/api/admin/fifa/matches/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/events'
    | '/full-execom'
    | '/societies'
    | '/FIFA/dashboard'
    | '/FIFA/feed'
    | '/FIFA/leaderboard'
    | '/FIFA/matches'
    | '/FIFA/rules'
    | '/admin/blogs'
    | '/admin/check-in'
    | '/admin/dashboard'
    | '/admin/users'
    | '/api/registrations'
    | '/blog/$slug'
    | '/register/$eventId'
    | '/ticket/$ticketId'
    | '/FIFA/'
    | '/blog/'
    | '/FIFA/matches/$id'
    | '/admin/FIFA/raffle'
    | '/admin/FIFA/settings'
    | '/admin/FIFA/testing'
    | '/admin/events/new'
    | '/admin/execom/new'
    | '/admin/registrations/$id'
    | '/admin/societies/new'
    | '/api/admin/events'
    | '/api/admin/execom'
    | '/api/admin/registrations'
    | '/api/admin/societies'
    | '/api/admin/stats'
    | '/api/admin/users'
    | '/api/auth/init'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/check-in/verify'
    | '/api/events/$id'
    | '/api/events/validate-coupon'
    | '/api/fifa/bets'
    | '/api/fifa/dashboard'
    | '/api/fifa/live-scores'
    | '/api/fifa/matches'
    | '/api/files/$'
    | '/api/society/$slug'
    | '/api/ticket/$ticketId'
    | '/admin/events/'
    | '/admin/execom/'
    | '/admin/registrations/'
    | '/admin/societies/'
    | '/admin/FIFA/matches/$id'
    | '/admin/events/$id/edit'
    | '/admin/execom/$id/edit'
    | '/admin/societies/$id/edit'
    | '/api/admin/events/$id'
    | '/api/admin/execom/$id'
    | '/api/admin/fifa/bets'
    | '/api/admin/fifa/markets'
    | '/api/admin/fifa/matches'
    | '/api/admin/fifa/raffle'
    | '/api/admin/fifa/raffle-draws'
    | '/api/admin/fifa/settings'
    | '/api/admin/fifa/settle'
    | '/api/admin/fifa/testing'
    | '/api/admin/registrations/$id'
    | '/api/admin/societies/$id'
    | '/api/auth/callback/google'
    | '/api/events/$id/export'
    | '/admin/FIFA/matches/'
    | '/api/admin/events/$id/coupons'
    | '/api/admin/events/$id/registrations-csv'
    | '/api/admin/fifa/markets/$id'
    | '/api/admin/fifa/matches/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  EventsRoute: typeof EventsRoute
  FullExecomRoute: typeof FullExecomRoute
  SocietiesRoute: typeof SocietiesRoute
  FIFADashboardRoute: typeof FIFADashboardRoute
  FIFAFeedRoute: typeof FIFAFeedRoute
  FIFALeaderboardRoute: typeof FIFALeaderboardRoute
  FIFAMatchesRoute: typeof FIFAMatchesRouteWithChildren
  FIFARulesRoute: typeof FIFARulesRoute
  ApiRegistrationsRoute: typeof ApiRegistrationsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  RegisterEventIdRoute: typeof RegisterEventIdRoute
  TicketTicketIdRoute: typeof TicketTicketIdRoute
  FIFAIndexRoute: typeof FIFAIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiAdminEventsRoute: typeof ApiAdminEventsRouteWithChildren
  ApiAdminExecomRoute: typeof ApiAdminExecomRouteWithChildren
  ApiAdminRegistrationsRoute: typeof ApiAdminRegistrationsRouteWithChildren
  ApiAdminSocietiesRoute: typeof ApiAdminSocietiesRouteWithChildren
  ApiAdminStatsRoute: typeof ApiAdminStatsRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAuthInitRoute: typeof ApiAuthInitRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiCheckInVerifyRoute: typeof ApiCheckInVerifyRoute
  ApiEventsIdRoute: typeof ApiEventsIdRouteWithChildren
  ApiEventsValidateCouponRoute: typeof ApiEventsValidateCouponRoute
  ApiFifaBetsRoute: typeof ApiFifaBetsRoute
  ApiFifaDashboardRoute: typeof ApiFifaDashboardRoute
  ApiFifaLiveScoresRoute: typeof ApiFifaLiveScoresRoute
  ApiFifaMatchesRoute: typeof ApiFifaMatchesRoute
  ApiFilesSplatRoute: typeof ApiFilesSplatRoute
  ApiSocietySlugRoute: typeof ApiSocietySlugRoute
  ApiTicketTicketIdRoute: typeof ApiTicketTicketIdRoute
  ApiAdminFifaBetsRoute: typeof ApiAdminFifaBetsRoute
  ApiAdminFifaMarketsRoute: typeof ApiAdminFifaMarketsRouteWithChildren
  ApiAdminFifaMatchesRoute: typeof ApiAdminFifaMatchesRouteWithChildren
  ApiAdminFifaRaffleRoute: typeof ApiAdminFifaRaffleRoute
  ApiAdminFifaRaffleDrawsRoute: typeof ApiAdminFifaRaffleDrawsRoute
  ApiAdminFifaSettingsRoute: typeof ApiAdminFifaSettingsRoute
  ApiAdminFifaSettleRoute: typeof ApiAdminFifaSettleRoute
  ApiAdminFifaTestingRoute: typeof ApiAdminFifaTestingRoute
  ApiAuthCallbackGoogleRoute: typeof ApiAuthCallbackGoogleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/societies': {
      id: '/societies'
      path: '/societies'
      fullPath: '/societies'
      preLoaderRoute: typeof SocietiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/full-execom': {
      id: '/full-execom'
      path: '/full-execom'
      fullPath: '/full-execom'
      preLoaderRoute: typeof FullExecomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/FIFA/': {
      id: '/FIFA/'
      path: '/FIFA'
      fullPath: '/FIFA/'
      preLoaderRoute: typeof FIFAIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$ticketId': {
      id: '/ticket/$ticketId'
      path: '/ticket/$ticketId'
      fullPath: '/ticket/$ticketId'
      preLoaderRoute: typeof TicketTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/$eventId': {
      id: '/register/$eventId'
      path: '/register/$eventId'
      fullPath: '/register/$eventId'
      preLoaderRoute: typeof RegisterEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/registrations': {
      id: '/api/registrations'
      path: '/api/registrations'
      fullPath: '/api/registrations'
      preLoaderRoute: typeof ApiRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/check-in': {
      id: '/admin/check-in'
      path: '/check-in'
      fullPath: '/admin/check-in'
      preLoaderRoute: typeof AdminCheckInRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/FIFA/rules': {
      id: '/FIFA/rules'
      path: '/FIFA/rules'
      fullPath: '/FIFA/rules'
      preLoaderRoute: typeof FIFARulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/FIFA/matches': {
      id: '/FIFA/matches'
      path: '/FIFA/matches'
      fullPath: '/FIFA/matches'
      preLoaderRoute: typeof FIFAMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/FIFA/leaderboard': {
      id: '/FIFA/leaderboard'
      path: '/FIFA/leaderboard'
      fullPath: '/FIFA/leaderboard'
      preLoaderRoute: typeof FIFALeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/FIFA/feed': {
      id: '/FIFA/feed'
      path: '/FIFA/feed'
      fullPath: '/FIFA/feed'
      preLoaderRoute: typeof FIFAFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/FIFA/dashboard': {
      id: '/FIFA/dashboard'
      path: '/FIFA/dashboard'
      fullPath: '/FIFA/dashboard'
      preLoaderRoute: typeof FIFADashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/societies/': {
      id: '/admin/societies/'
      path: '/societies'
      fullPath: '/admin/societies/'
      preLoaderRoute: typeof AdminSocietiesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/registrations/': {
      id: '/admin/registrations/'
      path: '/registrations'
      fullPath: '/admin/registrations/'
      preLoaderRoute: typeof AdminRegistrationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/execom/': {
      id: '/admin/execom/'
      path: '/execom'
      fullPath: '/admin/execom/'
      preLoaderRoute: typeof AdminExecomIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/ticket/$ticketId': {
      id: '/api/ticket/$ticketId'
      path: '/api/ticket/$ticketId'
      fullPath: '/api/ticket/$ticketId'
      preLoaderRoute: typeof ApiTicketTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/society/$slug': {
      id: '/api/society/$slug'
      path: '/api/society/$slug'
      fullPath: '/api/society/$slug'
      preLoaderRoute: typeof ApiSocietySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$': {
      id: '/api/files/$'
      path: '/api/files/$'
      fullPath: '/api/files/$'
      preLoaderRoute: typeof ApiFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fifa/matches': {
      id: '/api/fifa/matches'
      path: '/api/fifa/matches'
      fullPath: '/api/fifa/matches'
      preLoaderRoute: typeof ApiFifaMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fifa/live-scores': {
      id: '/api/fifa/live-scores'
      path: '/api/fifa/live-scores'
      fullPath: '/api/fifa/live-scores'
      preLoaderRoute: typeof ApiFifaLiveScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fifa/dashboard': {
      id: '/api/fifa/dashboard'
      path: '/api/fifa/dashboard'
      fullPath: '/api/fifa/dashboard'
      preLoaderRoute: typeof ApiFifaDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fifa/bets': {
      id: '/api/fifa/bets'
      path: '/api/fifa/bets'
      fullPath: '/api/fifa/bets'
      preLoaderRoute: typeof ApiFifaBetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/validate-coupon': {
      id: '/api/events/validate-coupon'
      path: '/api/events/validate-coupon'
      fullPath: '/api/events/validate-coupon'
      preLoaderRoute: typeof ApiEventsValidateCouponRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/$id': {
      id: '/api/events/$id'
      path: '/api/events/$id'
      fullPath: '/api/events/$id'
      preLoaderRoute: typeof ApiEventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/check-in/verify': {
      id: '/api/check-in/verify'
      path: '/api/check-in/verify'
      fullPath: '/api/check-in/verify'
      preLoaderRoute: typeof ApiCheckInVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/init': {
      id: '/api/auth/init'
      path: '/api/auth/init'
      fullPath: '/api/auth/init'
      preLoaderRoute: typeof ApiAuthInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stats': {
      id: '/api/admin/stats'
      path: '/api/admin/stats'
      fullPath: '/api/admin/stats'
      preLoaderRoute: typeof ApiAdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/societies': {
      id: '/api/admin/societies'
      path: '/api/admin/societies'
      fullPath: '/api/admin/societies'
      preLoaderRoute: typeof ApiAdminSocietiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/registrations': {
      id: '/api/admin/registrations'
      path: '/api/admin/registrations'
      fullPath: '/api/admin/registrations'
      preLoaderRoute: typeof ApiAdminRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/execom': {
      id: '/api/admin/execom'
      path: '/api/admin/execom'
      fullPath: '/api/admin/execom'
      preLoaderRoute: typeof ApiAdminExecomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/events': {
      id: '/api/admin/events'
      path: '/api/admin/events'
      fullPath: '/api/admin/events'
      preLoaderRoute: typeof ApiAdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/societies/new': {
      id: '/admin/societies/new'
      path: '/societies/new'
      fullPath: '/admin/societies/new'
      preLoaderRoute: typeof AdminSocietiesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/registrations/$id': {
      id: '/admin/registrations/$id'
      path: '/registrations/$id'
      fullPath: '/admin/registrations/$id'
      preLoaderRoute: typeof AdminRegistrationsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/execom/new': {
      id: '/admin/execom/new'
      path: '/execom/new'
      fullPath: '/admin/execom/new'
      preLoaderRoute: typeof AdminExecomNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/new': {
      id: '/admin/events/new'
      path: '/events/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AdminEventsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/FIFA/testing': {
      id: '/admin/FIFA/testing'
      path: '/FIFA/testing'
      fullPath: '/admin/FIFA/testing'
      preLoaderRoute: typeof AdminFIFATestingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/FIFA/settings': {
      id: '/admin/FIFA/settings'
      path: '/FIFA/settings'
      fullPath: '/admin/FIFA/settings'
      preLoaderRoute: typeof AdminFIFASettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/FIFA/raffle': {
      id: '/admin/FIFA/raffle'
      path: '/FIFA/raffle'
      fullPath: '/admin/FIFA/raffle'
      preLoaderRoute: typeof AdminFIFARaffleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/FIFA/matches/$id': {
      id: '/FIFA/matches/$id'
      path: '/$id'
      fullPath: '/FIFA/matches/$id'
      preLoaderRoute: typeof FIFAMatchesIdRouteImport
      parentRoute: typeof FIFAMatchesRoute
    }
    '/admin/FIFA/matches/': {
      id: '/admin/FIFA/matches/'
      path: '/FIFA/matches'
      fullPath: '/admin/FIFA/matches/'
      preLoaderRoute: typeof AdminFIFAMatchesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/events/$id/export': {
      id: '/api/events/$id/export'
      path: '/export'
      fullPath: '/api/events/$id/export'
      preLoaderRoute: typeof ApiEventsIdExportRouteImport
      parentRoute: typeof ApiEventsIdRoute
    }
    '/api/auth/callback/google': {
      id: '/api/auth/callback/google'
      path: '/api/auth/callback/google'
      fullPath: '/api/auth/callback/google'
      preLoaderRoute: typeof ApiAuthCallbackGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/societies/$id': {
      id: '/api/admin/societies/$id'
      path: '/$id'
      fullPath: '/api/admin/societies/$id'
      preLoaderRoute: typeof ApiAdminSocietiesIdRouteImport
      parentRoute: typeof ApiAdminSocietiesRoute
    }
    '/api/admin/registrations/$id': {
      id: '/api/admin/registrations/$id'
      path: '/$id'
      fullPath: '/api/admin/registrations/$id'
      preLoaderRoute: typeof ApiAdminRegistrationsIdRouteImport
      parentRoute: typeof ApiAdminRegistrationsRoute
    }
    '/api/admin/fifa/testing': {
      id: '/api/admin/fifa/testing'
      path: '/api/admin/fifa/testing'
      fullPath: '/api/admin/fifa/testing'
      preLoaderRoute: typeof ApiAdminFifaTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/fifa/settle': {
      id: '/api/admin/fifa/settle'
      path: '/api/admin/fifa/settle'
      fullPath: '/api/admin/fifa/settle'
      preLoaderRoute: typeof ApiAdminFifaSettleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/fifa/settings': {
      id: '/api/admin/fifa/settings'
      path: '/api/admin/fifa/settings'
      fullPath: '/api/admin/fifa/settings'
      preLoaderRoute: typeof ApiAdminFifaSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/fifa/raffle-draws': {
      id: '/api/admin/fifa/raffle-draws'
      path: '/api/admin/fifa/raffle-draws'
      fullPath: '/api/admin/fifa/raffle-draws'
      preLoaderRoute: typeof ApiAdminFifaRaffleDrawsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/fifa/raffle': {
      id: '/api/admin/fifa/raffle'
      path: '/api/admin/fifa/raffle'
      fullPath: '/api/admin/fifa/raffle'
      preLoaderRoute: typeof ApiAdminFifaRaffleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/fifa/matches': {
      id: '/api/admin/fifa/matches'
      path: '/api/admin/fifa/matches'
      fullPath: '/api/admin/fifa/matches'
      preLoaderRoute: typeof ApiAdminFifaMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/fifa/markets': {
      id: '/api/admin/fifa/markets'
      path: '/api/admin/fifa/markets'
      fullPath: '/api/admin/fifa/markets'
      preLoaderRoute: typeof ApiAdminFifaMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/fifa/bets': {
      id: '/api/admin/fifa/bets'
      path: '/api/admin/fifa/bets'
      fullPath: '/api/admin/fifa/bets'
      preLoaderRoute: typeof ApiAdminFifaBetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/execom/$id': {
      id: '/api/admin/execom/$id'
      path: '/$id'
      fullPath: '/api/admin/execom/$id'
      preLoaderRoute: typeof ApiAdminExecomIdRouteImport
      parentRoute: typeof ApiAdminExecomRoute
    }
    '/api/admin/events/$id': {
      id: '/api/admin/events/$id'
      path: '/$id'
      fullPath: '/api/admin/events/$id'
      preLoaderRoute: typeof ApiAdminEventsIdRouteImport
      parentRoute: typeof ApiAdminEventsRoute
    }
    '/admin/societies/$id/edit': {
      id: '/admin/societies/$id/edit'
      path: '/societies/$id/edit'
      fullPath: '/admin/societies/$id/edit'
      preLoaderRoute: typeof AdminSocietiesIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/execom/$id/edit': {
      id: '/admin/execom/$id/edit'
      path: '/execom/$id/edit'
      fullPath: '/admin/execom/$id/edit'
      preLoaderRoute: typeof AdminExecomIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/$id/edit': {
      id: '/admin/events/$id/edit'
      path: '/events/$id/edit'
      fullPath: '/admin/events/$id/edit'
      preLoaderRoute: typeof AdminEventsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/FIFA/matches/$id': {
      id: '/admin/FIFA/matches/$id'
      path: '/FIFA/matches/$id'
      fullPath: '/admin/FIFA/matches/$id'
      preLoaderRoute: typeof AdminFIFAMatchesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin/fifa/matches/$id': {
      id: '/api/admin/fifa/matches/$id'
      path: '/$id'
      fullPath: '/api/admin/fifa/matches/$id'
      preLoaderRoute: typeof ApiAdminFifaMatchesIdRouteImport
      parentRoute: typeof ApiAdminFifaMatchesRoute
    }
    '/api/admin/fifa/markets/$id': {
      id: '/api/admin/fifa/markets/$id'
      path: '/$id'
      fullPath: '/api/admin/fifa/markets/$id'
      preLoaderRoute: typeof ApiAdminFifaMarketsIdRouteImport
      parentRoute: typeof ApiAdminFifaMarketsRoute
    }
    '/api/admin/events/$id/registrations-csv': {
      id: '/api/admin/events/$id/registrations-csv'
      path: '/registrations-csv'
      fullPath: '/api/admin/events/$id/registrations-csv'
      preLoaderRoute: typeof ApiAdminEventsIdRegistrationsCsvRouteImport
      parentRoute: typeof ApiAdminEventsIdRoute
    }
    '/api/admin/events/$id/coupons': {
      id: '/api/admin/events/$id/coupons'
      path: '/coupons'
      fullPath: '/api/admin/events/$id/coupons'
      preLoaderRoute: typeof ApiAdminEventsIdCouponsRouteImport
      parentRoute: typeof ApiAdminEventsIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminCheckInRoute: typeof AdminCheckInRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminFIFARaffleRoute: typeof AdminFIFARaffleRoute
  AdminFIFASettingsRoute: typeof AdminFIFASettingsRoute
  AdminFIFATestingRoute: typeof AdminFIFATestingRoute
  AdminEventsNewRoute: typeof AdminEventsNewRoute
  AdminExecomNewRoute: typeof AdminExecomNewRoute
  AdminRegistrationsIdRoute: typeof AdminRegistrationsIdRoute
  AdminSocietiesNewRoute: typeof AdminSocietiesNewRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
  AdminExecomIndexRoute: typeof AdminExecomIndexRoute
  AdminRegistrationsIndexRoute: typeof AdminRegistrationsIndexRoute
  AdminSocietiesIndexRoute: typeof AdminSocietiesIndexRoute
  AdminFIFAMatchesIdRoute: typeof AdminFIFAMatchesIdRoute
  AdminEventsIdEditRoute: typeof AdminEventsIdEditRoute
  AdminExecomIdEditRoute: typeof AdminExecomIdEditRoute
  AdminSocietiesIdEditRoute: typeof AdminSocietiesIdEditRoute
  AdminFIFAMatchesIndexRoute: typeof AdminFIFAMatchesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogsRoute: AdminBlogsRoute,
  AdminCheckInRoute: AdminCheckInRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminFIFARaffleRoute: AdminFIFARaffleRoute,
  AdminFIFASettingsRoute: AdminFIFASettingsRoute,
  AdminFIFATestingRoute: AdminFIFATestingRoute,
  AdminEventsNewRoute: AdminEventsNewRoute,
  AdminExecomNewRoute: AdminExecomNewRoute,
  AdminRegistrationsIdRoute: AdminRegistrationsIdRoute,
  AdminSocietiesNewRoute: AdminSocietiesNewRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  AdminExecomIndexRoute: AdminExecomIndexRoute,
  AdminRegistrationsIndexRoute: AdminRegistrationsIndexRoute,
  AdminSocietiesIndexRoute: AdminSocietiesIndexRoute,
  AdminFIFAMatchesIdRoute: AdminFIFAMatchesIdRoute,
  AdminEventsIdEditRoute: AdminEventsIdEditRoute,
  AdminExecomIdEditRoute: AdminExecomIdEditRoute,
  AdminSocietiesIdEditRoute: AdminSocietiesIdEditRoute,
  AdminFIFAMatchesIndexRoute: AdminFIFAMatchesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface FIFAMatchesRouteChildren {
  FIFAMatchesIdRoute: typeof FIFAMatchesIdRoute
}

const FIFAMatchesRouteChildren: FIFAMatchesRouteChildren = {
  FIFAMatchesIdRoute: FIFAMatchesIdRoute,
}

const FIFAMatchesRouteWithChildren = FIFAMatchesRoute._addFileChildren(
  FIFAMatchesRouteChildren,
)

interface ApiAdminEventsIdRouteChildren {
  ApiAdminEventsIdCouponsRoute: typeof ApiAdminEventsIdCouponsRoute
  ApiAdminEventsIdRegistrationsCsvRoute: typeof ApiAdminEventsIdRegistrationsCsvRoute
}

const ApiAdminEventsIdRouteChildren: ApiAdminEventsIdRouteChildren = {
  ApiAdminEventsIdCouponsRoute: ApiAdminEventsIdCouponsRoute,
  ApiAdminEventsIdRegistrationsCsvRoute: ApiAdminEventsIdRegistrationsCsvRoute,
}

const ApiAdminEventsIdRouteWithChildren =
  ApiAdminEventsIdRoute._addFileChildren(ApiAdminEventsIdRouteChildren)

interface ApiAdminEventsRouteChildren {
  ApiAdminEventsIdRoute: typeof ApiAdminEventsIdRouteWithChildren
}

const ApiAdminEventsRouteChildren: ApiAdminEventsRouteChildren = {
  ApiAdminEventsIdRoute: ApiAdminEventsIdRouteWithChildren,
}

const ApiAdminEventsRouteWithChildren = ApiAdminEventsRoute._addFileChildren(
  ApiAdminEventsRouteChildren,
)

interface ApiAdminExecomRouteChildren {
  ApiAdminExecomIdRoute: typeof ApiAdminExecomIdRoute
}

const ApiAdminExecomRouteChildren: ApiAdminExecomRouteChildren = {
  ApiAdminExecomIdRoute: ApiAdminExecomIdRoute,
}

const ApiAdminExecomRouteWithChildren = ApiAdminExecomRoute._addFileChildren(
  ApiAdminExecomRouteChildren,
)

interface ApiAdminRegistrationsRouteChildren {
  ApiAdminRegistrationsIdRoute: typeof ApiAdminRegistrationsIdRoute
}

const ApiAdminRegistrationsRouteChildren: ApiAdminRegistrationsRouteChildren = {
  ApiAdminRegistrationsIdRoute: ApiAdminRegistrationsIdRoute,
}

const ApiAdminRegistrationsRouteWithChildren =
  ApiAdminRegistrationsRoute._addFileChildren(
    ApiAdminRegistrationsRouteChildren,
  )

interface ApiAdminSocietiesRouteChildren {
  ApiAdminSocietiesIdRoute: typeof ApiAdminSocietiesIdRoute
}

const ApiAdminSocietiesRouteChildren: ApiAdminSocietiesRouteChildren = {
  ApiAdminSocietiesIdRoute: ApiAdminSocietiesIdRoute,
}

const ApiAdminSocietiesRouteWithChildren =
  ApiAdminSocietiesRoute._addFileChildren(ApiAdminSocietiesRouteChildren)

interface ApiEventsIdRouteChildren {
  ApiEventsIdExportRoute: typeof ApiEventsIdExportRoute
}

const ApiEventsIdRouteChildren: ApiEventsIdRouteChildren = {
  ApiEventsIdExportRoute: ApiEventsIdExportRoute,
}

const ApiEventsIdRouteWithChildren = ApiEventsIdRoute._addFileChildren(
  ApiEventsIdRouteChildren,
)

interface ApiAdminFifaMarketsRouteChildren {
  ApiAdminFifaMarketsIdRoute: typeof ApiAdminFifaMarketsIdRoute
}

const ApiAdminFifaMarketsRouteChildren: ApiAdminFifaMarketsRouteChildren = {
  ApiAdminFifaMarketsIdRoute: ApiAdminFifaMarketsIdRoute,
}

const ApiAdminFifaMarketsRouteWithChildren =
  ApiAdminFifaMarketsRoute._addFileChildren(ApiAdminFifaMarketsRouteChildren)

interface ApiAdminFifaMatchesRouteChildren {
  ApiAdminFifaMatchesIdRoute: typeof ApiAdminFifaMatchesIdRoute
}

const ApiAdminFifaMatchesRouteChildren: ApiAdminFifaMatchesRouteChildren = {
  ApiAdminFifaMatchesIdRoute: ApiAdminFifaMatchesIdRoute,
}

const ApiAdminFifaMatchesRouteWithChildren =
  ApiAdminFifaMatchesRoute._addFileChildren(ApiAdminFifaMatchesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  EventsRoute: EventsRoute,
  FullExecomRoute: FullExecomRoute,
  SocietiesRoute: SocietiesRoute,
  FIFADashboardRoute: FIFADashboardRoute,
  FIFAFeedRoute: FIFAFeedRoute,
  FIFALeaderboardRoute: FIFALeaderboardRoute,
  FIFAMatchesRoute: FIFAMatchesRouteWithChildren,
  FIFARulesRoute: FIFARulesRoute,
  ApiRegistrationsRoute: ApiRegistrationsRoute,
  BlogSlugRoute: BlogSlugRoute,
  RegisterEventIdRoute: RegisterEventIdRoute,
  TicketTicketIdRoute: TicketTicketIdRoute,
  FIFAIndexRoute: FIFAIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiAdminEventsRoute: ApiAdminEventsRouteWithChildren,
  ApiAdminExecomRoute: ApiAdminExecomRouteWithChildren,
  ApiAdminRegistrationsRoute: ApiAdminRegistrationsRouteWithChildren,
  ApiAdminSocietiesRoute: ApiAdminSocietiesRouteWithChildren,
  ApiAdminStatsRoute: ApiAdminStatsRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAuthInitRoute: ApiAuthInitRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiCheckInVerifyRoute: ApiCheckInVerifyRoute,
  ApiEventsIdRoute: ApiEventsIdRouteWithChildren,
  ApiEventsValidateCouponRoute: ApiEventsValidateCouponRoute,
  ApiFifaBetsRoute: ApiFifaBetsRoute,
  ApiFifaDashboardRoute: ApiFifaDashboardRoute,
  ApiFifaLiveScoresRoute: ApiFifaLiveScoresRoute,
  ApiFifaMatchesRoute: ApiFifaMatchesRoute,
  ApiFilesSplatRoute: ApiFilesSplatRoute,
  ApiSocietySlugRoute: ApiSocietySlugRoute,
  ApiTicketTicketIdRoute: ApiTicketTicketIdRoute,
  ApiAdminFifaBetsRoute: ApiAdminFifaBetsRoute,
  ApiAdminFifaMarketsRoute: ApiAdminFifaMarketsRouteWithChildren,
  ApiAdminFifaMatchesRoute: ApiAdminFifaMatchesRouteWithChildren,
  ApiAdminFifaRaffleRoute: ApiAdminFifaRaffleRoute,
  ApiAdminFifaRaffleDrawsRoute: ApiAdminFifaRaffleDrawsRoute,
  ApiAdminFifaSettingsRoute: ApiAdminFifaSettingsRoute,
  ApiAdminFifaSettleRoute: ApiAdminFifaSettleRoute,
  ApiAdminFifaTestingRoute: ApiAdminFifaTestingRoute,
  ApiAuthCallbackGoogleRoute: ApiAuthCallbackGoogleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
